version: '3.4'
networks:
  frontend:
  backend:
services:
  eventcatalog:
    image: event/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7810
      DatabaseServer: mssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7810:80"
    depends_on:
      - mssqlserver
    networks:
      - frontend
      - backend
    container_name: EventProductserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: jewels/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7811
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: event/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.86.242:7800
      DatabaseServer: mssqlserver
      DatabaseName: OrderDB
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7850:80" 
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: event/cartapi
    environment:
      IdentityUrl: http://192.168.86.242:7800
      ConnectionString: basketdata
    ports:
      - "7840:80"
    container_name: cartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basketdata

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      EventUrl: http://eventcatalog
      IdentityUrl: http://192.168.86.242:7800
      CallBackUrl: http://localhost:7811
      CartUrl: http://cart
    ports:
      - "7811:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - tokenserver
      - cart
      - order

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: mssqlserver
    networks:
      - backend

  basketdata:
    image: redis
    container_name: databasket
    ports:
      - "7180:6379"
    networks:
      - backend