version: '3.4'
networks:
  frontend:
  backend:
services:
  eventcatalog:
    image: event/eventcatalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7810
      DatabaseServer: mssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7810:80"
    depends_on:
      - mssqlserver
    networks:
      - frontend
      - backend
    container_name: EventProductserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://webmvc
    ports:
      - "7800:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver


  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      EventUrl: http://eventcatalog
      IdentityUrl: http://http://10.1.10.224:7800
      CallbackUrl: http://localhost:7811
    ports:
      - "7811:80"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - eventcatalog
      - tokenserver
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1433"
    container_name: mssqlserver
    networks:
      - backend